name: C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install GoogleTest
      run: |
        git clone https://github.com/google/googletest.git -b release-1.12.1
        mkdir -p googletest/build
        cd googletest/build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install
    - name: Binary build and test
      run: |
        cd ${{ github.workspace }}
        make test
